bus_stop_lineNumbers:
    path:     /getLineTypes
    defaults: { _controller: BusStopBundle:Default:getLineTypes }

bus_stop_message:
    path:     /getMessage
    defaults: { _controller: BusStopBundle:Default:getMessage }
