bus_stop_lineNumbers:
    path:     /getLineTypes
    defaults: { _controller: BusStopBundle:Default:getLineTypes }

bus_stop_message:
    path:     /getMessage
    defaults: { _controller: BusStopBundle:Default:getMessage }

bus_stop_busstopname:
    path:     /getBusStopName
    defaults: { _controller: BusStopBundle:Default:getBusStopName }

bus_stop_arrivals:
    path:     /getTimeTable
    defaults: { _controller: BusStopBundle:Default:getTimeTable }
